# Generated by Django 2.2 on 2021-10-07 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=40)),
                ('c_img', models.ImageField(upload_to='CatImg')),
                ('c_status', models.CharField(choices=[('hide', 'Hide'), ('show', 'Show')], default='hide', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('b_img', models.ImageField(upload_to='blogImage')),
                ('slug', models.SlugField(max_length=70)),
                ('b_status', models.CharField(choices=[('hide', 'Hide'), ('show', 'Show')], default='hide', max_length=20)),
                ('b_create', models.DateTimeField(auto_now_add=True)),
                ('b_update', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
                ('b_cat', models.ForeignKey(on_delete=False, to='blog.Cate')),
            ],
        ),
    ]
