# Generated by Django 2.2 on 2021-10-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
