# Generated by Django 2.2 on 2021-10-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211009_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='body',
            field=models.TextField(),
        ),
    ]
