# Generated by Django 2.2 on 2021-10-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BascicSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(blank=True, upload_to='icon')),
                ('facebook', models.URLField(max_length=300)),
                ('twitter', models.URLField(max_length=300)),
                ('instagram', models.URLField(max_length=300)),
                ('driblelink', models.URLField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.IntegerField(max_length=10)),
                ('pinterest', models.URLField(max_length=300)),
            ],
        ),
    ]
