# Generated by Django 2.2 on 2021-10-26 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211022_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='b_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Cate'),
        ),
    ]
