# Generated by Django 2.2 on 2021-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211026_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='b_cat',
            field=models.ForeignKey(on_delete=False, to='blog.Cate'),
        ),
    ]
