# Generated by Django 2.2 on 2021-10-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211026_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='./static/images/awatar.jpg', upload_to='profile_img'),
        ),
    ]
