# Generated by Django 2.2 on 2021-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20211029_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bascicsettings',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icon'),
        ),
    ]
