# Generated by Django 2.2 on 2021-11-01 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211029_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='calvin/static/images/awatar.jpg', upload_to='profile_img'),
        ),
    ]
