# Generated by Django 2.2 on 2021-11-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20211101_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='awatar.jpg', upload_to='profile_img'),
        ),
    ]
